# API reference documentation generator configuration
# See: ./_apidocgen/README.md

[autonity]
build_dir = "params/generated"
src_dir = "autonity/solidity/contracts"
github_url = "https://github.com/autonity/autonity"

[contracts]
output_dir = "reference/api"

[contracts.Accountability]
excludes = [
  # onlyAutonity
  "distributeRewards",
  "finalize",
  "setEpochPeriod",
  # onlyValidator
  "handleEvent",
]

[contracts.ACU]
excludes = [
  # onlyAutonity
  "setOperator",
  "setOracle",
  "update",
]

[contracts.Autonity]
excludes = [
  # onlyAccountability
  "updateValidatorAndTransferSlashedFunds",
  # onlyOperator
  "burn",
  "mint",
  "setAccountabilityContract",
  "setAcuContract",
  "setCommitteeSize",
  "setEpochPeriod",
  "setInflationControllerContract",
  "setMaxBondAppliedGas",
  "setMaxRewardsDistributionGas",
  "setMaxUnbondAppliedGas",
  "setMaxUnbondReleasedGas",
  "setMinimumBaseFee",
  "setNonStakableVestingContract",
  "setOperatorAccount",
  "setOracleContract",
  "setStabilizationContract",
  "setStakingGasPrice",
  "setSupplyControlContract",
  "setTreasuryAccount",
  "setTreasuryFee",
  "setUnbondingPeriod",
  "setUpgradeManagerContract",
  # onlyProtocol
  "computeCommittee",
  "finalize",
  "finalizeInitialization",
]

[contracts.Liquid]
display_name = "Liquid Newton"
excludes = [
  # onlyAutonity
  "burn",
  "lock",
  "mint",
  "redistribute",
  "setCommissionRate",
  "unlock",
]

[contracts.Oracle]
excludes = [
  # onlyAutonity
  "finalize",
  "setOperator",
  "setVoters",
  # onlyOperator
  "setSymbols",
  # onlyVoters
  "vote",
]

[contracts.Stabilization]
excludes = [
  # onlyAutonity
  "setOperator",
  "setOracle",
  # onlyOperator
  "setLiquidationRatio",
  "setMinCollateralizationRatio",
  "setMinDebtRequirement",
  "setSupplyControl",
]

[contracts.SupplyControl]
display_name = "Supply Control"
excludes = [
  # onlyAutonity
  "setOperator",
  # onlyOperator
  "setStabilizer",
  # onlyStabilizer
  "burn",
  "mint",
]
