# API reference documentation generator configuration
# See: ./_apidocgen/README.md

[autonity]
src_dir = "autonity/solidity/contracts"
github_url = "https://github.com/autonity/autonity"

[contracts]
output_dir = "reference/api"

[contracts.Accountability]
excludes = [
  # onlyAFDReporter
  "handleAccusation",
  "handleInnocenceProof",
  "handleMisbehaviour",
  # onlyAutonity
  "distributeRewards",
  "finalize",
  "setEpochPeriod",
  # onlyValidator
  "handleEvent",
]

[contracts.ACU]
excludes = [
  # onlyAutonity
  "setOperator",
  "setOracle",
  "update",
  # onlyOperator
  "modifyBasket",
]

[contracts.Autonity]
excludes = [
  # onlyAccountability
  "jail",
  "jailbound",
  "slash",
  "slashAndJail",
  # onlyOperator
  "burn",
  "mint",
  "completeContractUpgrade",
  "createSchedule",
  "resetContractUpgrade",
  "setAccountabilityContract",
  "setAcuContract",
  "setCommitteeSize",
  "setEpochPeriod",
  "setInflationControllerContract",
  "setLiquidLogicContract",
  "setMaxScheduleDuration",
  "setMinimumBaseFee",
  "setOmissionAccountabilityContract",
  "setOperatorAccount",
  "setOracleContract",
  "setOracleRewardRate",
  "setProposerRewardRate",
  "setSlasher",
  "setStabilizationContract",
  "setSupplyControlContract",
  "setTreasuryAccount",
  "setTreasuryFee",
  "setUnbondingPeriod",
  "setUpgradeManagerContract",
  "setWithholidingThreshold",
  "setWithheldRewardsPool",
  # onlyProtocol
  "computeCommittee",
  "finalize",
  "finalizeInitialization",
  # onlyRewardDistributor
  "autobond",
]

[contracts.LiquidLogic]
display_name = "Liquid Newton"
excludes = [
  # onlyAutonity
  "burn",
  "lock",
  "mint",
  "redistribute",
  "setCommissionRate",
  "unlock",
]

[contracts.Oracle]
excludes = [
  # onlyAutonity
  "distributeRewards",
  "finalize",
  "setOperator",
  "setVoters",
  "updateVoters",
  # onlyOperator
  "setSlashingConfig",
  "setSymbols",
  "setVotePeriod",
  # onlyVoters
  "vote",
]

[contracts.Stabilization]
excludes = [
  # onlyAutonity
  "setOperator",
  "setOracle",
  # onlyOperator
  "removeCDPRestrictions",
  "setAtnSupplyOperator",
  "setLiquidationRatio",
  "setMinCollateralizationRatio",
  "setMinDebtRequirement",
  "setSupplyControl",
]

[contracts.SupplyControl]
display_name = "Supply Control"
excludes = [
  # onlyAutonity
  "setOperator",
  # onlyOperator
  "setStabilizer",
  # onlyStabilizer
  "burn",
  "mint",
]
