name = "docs.autonity.org"
type = "javascript"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
pages_build_output_dir = "./docs"

[[build.environment]]
name = "QUARTO_VERSION"
value = "1.5.56"  # The version of Quarto you want to install

[build]
command = "./install-quarto.sh && quarto render"

[build.upload]
# Path to your rendered static files after running Quarto render
dir = "./docs"

