name = "docs.autonity.org"
type = "javascript"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
pages_build_output_dir = "./docs"

[[build.environment]]
name = "QUARTO_VERSION"
value = "1.5.56"

[build]
command = "./install-quarto.sh && quarto render"

[build.upload]
dir = "./docs"
