#!/bin/bash
# Script for running apidocgen in watch mode and quarto in preview mode
# together in the same shell.

python3 -m _apidocgen --watch &
APIDOCGEN_PID=$!

quarto preview &
QUARTO_PID=$!

trap "kill ${APIDOCGEN_PID} ${QUARTO_PID}" SIGINT SIGTERM
wait ${APIDOCGEN_PID} ${QUARTO_PID}
