#!/usr/bin/env bash

# Find all links [text](/path/to/page)

# set -e
# set -x

errs=0
for l in `git grep -ho -e '](/[^)]\+)' -- content/docs/ | grep -v '.png' | grep -v '.svg'` ; do
    # Remove ]( and )
    l=${l#](}
    l=${l%)}

    # Remove any anchor `#anchor`
    link=`echo $l | sed -e 's/#.*//g'`

    if ! [ -d "content/docs"$link ] ; then
        echo "INVALID LINK: $link"
        for f in "$(git grep -ril "($link)")" ; do
            echo "  in file: $f"
        done

        errs=1
    fi
done

exit $errs
