#!/bin/bash

# The original file name to look for
ORIGINAL_NAME="_index.md"
# The new name to change to
NEW_NAME="index.md"

# Find and rename files recursively
find . -type f -name "$ORIGINAL_NAME" -exec bash -c 'mv "$0" "${0%/*}/'"$NEW_NAME"'"' {} \;

echo "All files named $ORIGINAL_NAME have been renamed to $NEW_NAME."
