on:
    pull_request:
        branches:
        - develop   
name: Cloudflare-preview
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        deployments: write
        pull-requests: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
  
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
  
        - name: Render and Publish
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: html
        - name: Publish to Cloudflare Pages
          id: cloudflare_deploy
          uses: cloudflare/pages-action@v1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: docs-autonity-org
            directory: ./docs
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}                                  
        - name: Log Cloudflare Pages Outputs
          run: |
            echo "Cloudflare Deployment ID: ${{ steps.cloudflare_deploy.outputs.id }}"
            echo "Cloudflare Deployment URL: ${{ steps.cloudflare_deploy.outputs.url }}"
            echo "Cloudflare Deployment Alias: ${{ steps.cloudflare_deploy.outputs.alias }}"
            echo "Cloudflare Deployment Environment: ${{ steps.cloudflare_deploy.outputs.environment }}"
            echo "Cloudflare Deployment Status: ${{ steps.cloudflare_deploy.outputs.status }}"
        - name: Post Cloudflare Preview Comment
          uses: actions/github-script@v6
          env:
            CF_URL: ${{ env.CF_URL }}
          with:
            script: |
                const comment = `
                ## Cloudflare Preview URL
                - **Preview**: [${process.env.CF_URL}](${process.env.CF_URL})
                `;
                github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
                });
