name: Deploy to Cloudflare Pages
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  cloudflare-deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish to Cloudflare Pages
        id: cloudflare_deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: docs-autonity-org
          directory: ./docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2
        with:
            message: |
              🚀 This branch can be previewed at ${{ steps.cloudflare_deploy.outputs.url }}
