on:
    pull_request:
        branches:
        - develop   
name: Cloudflare-preview
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        deployments: write
        pull-requests: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
  
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
  
        - name: Render and Publish
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: html
        - name: Publish to Cloudflare Pages
          uses: cloudflare/pages-action@v1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: docs-autonity-org
            directory: ./docs
            gitHubToken: ${{ secrets.GITHUB_TOKEN }} 
          # Step to extract the Cloudflare preview URL from the logs
        - name: Extract Cloudflare Preview URL
          id: extract_url
          run: |
            # Search for the Cloudflare preview URL in the deploy step output
            CF_URL=$(cat $GITHUB_STEP_SUMMARY | grep -oP 'https://[a-z0-9-]+\.docs-autonity-org\.pages\.dev')
            echo "Cloudflare Preview URL: $CF_URL"
                echo "CF_URL=$CF_URL" >> $GITHUB_ENV

        # Post a comment with the Cloudflare Preview URL
        - name: Post Cloudflare Preview Comment
          uses: actions/github-script@v6
          env:
            CF_URL: ${{ env.CF_URL }}
          with:
            script: |
                const comment = `
                ## Cloudflare Preview URL
                - **Preview**: [${process.env.CF_URL}](${process.env.CF_URL})
                `;
                github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
                });
