name: PR

on:
  pull_request:
    branches:
      - master
      - feature/sumida-upgrade

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.361

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        
        