name: Publish Production Site

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.361

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Archive site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Download site archive
        uses: actions/download-artifact@v4
        with:
          name: site
          path: docs/

      - name: Deploy to S3
        run: |
          aws s3 sync --delete ./docs s3://$AWS_S3_BUCKET
          aws cloudfront create-invalidation --distribution-id E2JSC1AZT8OHDX --paths "/*"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
